import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import React, {Suspense} from "react";
import Loading from "@/app/loading";
import Navbar from "@/components/Navbar";
import { MusicPlayerProvider } from '@/context/MusicPlayerContext';


export const metadata: Metadata = {
  title: "Hoytoba.vercel.ap - হয়তোবা.কম",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased relative flex flex-col min-h-screen`}
       suppressHydrationWarning={true}>
        <MusicPlayerProvider>

        
      <Navbar/>
      <main className="container flex-auto max-w-7xl mx-auto px-4 mt-24 lg:px-10 sm:px-4 md:px-8">
        <Suspense fallback={<Loading/>}>{children}</Suspense>
      </main>
      </MusicPlayerProvider>
      </body>
    </html>
  );
}


