export const API_URL = "https://api.bibijaan.com/v1";
export const POSTS_PER_PAGE = 9;
export const POST_API = "https://api.bibijaan.com/v1/get_posts";
export const ALBUM_API = "https://api.bibijaan.com/v1/media/album";
export const RECENT_POST_API = "https://api.bibijaan.com/v1/get_recent"
export const PAGE_API = "https://api.bibijaan.com/v1/get_page"
export const CATEGORY_API = "https://api.bibijaan.com/v1/get_page?&site=hoytoba&slug=category"
export const CATEGORY_POST = "https://api.bibijaan.com/v1/get_category_posts"
export const AUTHOR_API = "https://api.bibijaan.com/v1/get_page?&site=hoytoba&slug=author"